---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: data
  labels:
    service: postgresql
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
  selector:
    app: postgresql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-read-svc
  namespace: data
  labels:
    service: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
  selector:
    app: postgresql
