---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  namespace: data
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql-svc
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:17
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: rootPassword
            - name: POSTGRESQL_DATABASE
              value: db
            - name: LANG
              value: C.UTF-8
          ports:
            - name: postgresql
              containerPort: 3306
          volumeMounts:
            - name: postgresql-pvc
              mountPath: /var/lib/postgresql
            - name: postgresql-server-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgresql-server-initdb
          configMap:
            name: postgresql-server-initdb-config
  volumeClaimTemplates:
    - metadata:
        name: postgresql-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
