---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secret.yaml
patches:
  - path: ./deployment_patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: api-deploy
      namespace: api
  # - path: ./ingress_patch.yaml
  - path: ./ingress-tls_patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: api-ingress
      namespace: api
