---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: prd
spec:
  secretName: cert
  dnsNames:
    - ${DOMAIN}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
