---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-staging
  namespace: prd
spec:
  secretName: cert-staging
  dnsNames:
    - "${DOMAIN}"
  issuerRef:
    name: letsencrypt-issuer-staging
    kind: ClusterIssuer
