---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-config
  namespace: platform
stringData:
  configuration.yml: |
    jwt_secret: ${JWT_SECRET}
    server:
      host: 0.0.0.0
      port: 9091
      path: "ssoauth"
    log:
      level: debug
    authentication_backend:
      # Uncomment the following block to enable file authentication
      file:
        path: /config/users_database.yml
      # Uncomment the following block to enable LDAP authentication
      # ldap:
      #   implementation: custom
      #   url: 'ldap://ldap-svc:3890'
      #   timeout: 5s
      #   start_tls: false
      #   # base_dn: "dc=ldap,dc=example,dc=com"
      #   base_dn: "${LDAP_BASE_DN}"
      #   users_filter: "(&({username_attribute}={input})(objectClass=person))"
      #   additional_users_dn: "ou=people"
      #   additional_groups_dn: "ou=groups"
      #   username_attribute: "uid"
      #   display_name_attribute: 'displayName'
      #   mail_attribute: 'mail'
      #   group_name_attribute: 'cn'
      #   groups_filter: "(member={dn})"
      #   user: "uid=admin,ou=people,${LDAP_BASE_DN}"
      #   password: '${LDAP_ADMIN_PASSWORD}'
    access_control:
      default_policy: deny
      rules:
        - domain: ${DOMAIN}
          resources:
            - '^/ssoauth'
          policy: bypass
        - domain: ${DOMAIN}
          policy: one_factor
    session:
      name: authelia_session
      domain: ${DOMAIN}
      same_site: strict
      secret: ${SESSION_SECRET}
      expiration: '1h'
      inactivity: '5m'
    storage:
      local:
        path: /tmp/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /tmp/notification.txt
