---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: ./config_patch.yaml
    target:
      version: v1
      kind: Secret
      name: authelia-config
      namespace: platform
  - path: ./deployment_patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: authelia-deploy
      namespace: platform
  - path: ./ingress-tls_patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: authelia-ingress
      namespace: platform
