---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: prd
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:9.0.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: rootPassword
            - name: MYSQL_DATABASE
              value: db
            - name: LANG
              value: C.UTF-8
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-server-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-server-initdb
          configMap:
            name: mysql-server-initdb-config
  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
