---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-config
  namespace: platform
stringData:
  configuration.yml: |
    jwt_secret: ${JWT_SECRET}
    server:
      host: 0.0.0.0
      port: 9091
      path: "ssoauth"
    log:
      level: debug
    authentication_backend:
      file:
        path: /config/users_database.yml
    access_control:
      default_policy: deny
      rules:
        - domain: ${DOMAIN}
          resources:
            - '^/ssoauth'
          policy: bypass
        - domain: ${DOMAIN}
          policy: one_factor
    session:
      name: authelia_session
      domain: ${DOMAIN}
      same_site: strict
      secret: ${SESSION_SECRET}
      expiration: '1h'
      inactivity: '5m'
    storage:
      local:
        path: /tmp/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /tmp/notification.txt    
  users_database.yml: |
    users:
      john_doe:
        displayname: "John Doe"
        # "$argon2id$yourhash"
        password: "${USER_PASSWORD}"
        email: ${EMAIL}
        groups:
          - admins
