---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./secret.yaml
patches:
  - path: statefulset_patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgresql-statefulset
      namespace: platform
