---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  namespace: data
  labels:
    app: postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: "0.0.0"
  volumeClaimTemplates:
    - metadata:
        name: postgresql-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
