---
apiVersion: v1
kind: Service
metadata:
  name: ldap-svc
  namespace: platform
  labels:
    service: ldap
spec:
  type: ClusterIP
  ports:
    - name: ldap
      port: 3890
      protocol: TCP
    - name: ldaps
      port: 6390
      protocol: TCP
    - name: http
      port: 17170
      protocol: TCP
  selector:
    app: ldap
