---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ${DOCKER_IMAGE}
          env:
            - name: BOUND_IP_ADDRESS
              value: "0.0.0.0"
            - name: PORT
              value: "80"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: rootPassword
            - name: DATABASE_URL
              value: postgresql-statefulset-0.postgresql-svc.data:5432/db
            - name: DATABASE_READ_URL
              value: postgresql-read-svc.data:5432/db
          ports:
            - name: api
              containerPort: 80
